/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package MaxMspOsc-0.1.0.0 */
#define VERSION_MaxMspOsc "0.1.0.0"
#define MIN_VERSION_MaxMspOsc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)

/* package base-4.9.0.0 */
#define VERSION_base "4.9.0.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  9 || \
  (major1) == 4 && (major2) == 9 && (minor) <= 0)

/* package tidal-0.9.6 */
#define VERSION_tidal "0.9.6"
#define MIN_VERSION_tidal(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 6)

/* tool cpphs-1.20.2 */
#define TOOL_VERSION_cpphs "1.20.2"
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 2)

/* tool gcc-4.2.1 */
#define TOOL_VERSION_gcc "4.2.1"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  2 || \
  (major1) == 4 && (major2) == 2 && (minor) <= 1)

/* tool ghc-8.0.1 */
#define TOOL_VERSION_ghc "8.0.1"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 1)

/* tool ghc-pkg-8.0.1 */
#define TOOL_VERSION_ghc_pkg "8.0.1"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 1)

/* tool haddock-2.17.2 */
#define TOOL_VERSION_haddock "2.17.2"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 2)

/* tool happy-1.19.5 */
#define TOOL_VERSION_happy "1.19.5"
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 5)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.68 */
#define TOOL_VERSION_hsc2hs "0.68"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)

/* tool hscolour-1.24 */
#define TOOL_VERSION_hscolour "1.24"
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)

/* tool pkg-config-0.29.2 */
#define TOOL_VERSION_pkg_config "0.29.2"
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)

#define CURRENT_COMPONENT_ID "MaxMspOsc-0.1.0.0-CK6siUG6FC5HHsg7Bo0rkH"

#define CURRENT_PACKAGE_KEY "MaxMspOsc-0.1.0.0-CK6siUG6FC5HHsg7Bo0rkH"

